server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #github 仓库名字
          uri: https://github.com/jiangfendou/springcloud-config
          search-paths:
            - springcloud-config
          username: 49323245@qq.com
          password: 5211314jmh
      label: master
  #读取rabbitMQ的相关配置
  rabbitmq:
    host: 8.136.17.98
    port: 5672
    username: admin
    password: jmh123
# eureka client
eureka:
  client:
    # 表示是否将自己注册进eureka server 默认 true
    register-with-eureka: true
    # 表示是否冲eureka server抓取自己的注册信息，默认true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # Eureka 集群
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
