server:
  port: 83

spring:
  application:
    name: nacos-roder-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.17.98:8088
#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider